# Generated by Django 5.1.7 on 2025-05-13 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda'),
        ),
    ]
