# Generated by Django 5.1.7 on 2025-04-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anyo', models.DateField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
