# Generated by Django 5.1.8 on 2025-04-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('EU', 'Euros'), ('Dolar', 'Dolar'), ('LIB', 'Libra')], default='EU', max_length=5)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente')),
            ],
        ),
    ]
