# Generated by Django 5.1.8 on 2025-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='productos',
            field=models.ManyToManyField(through='tienda.Inventario', to='tienda.coche'),
        ),
    ]
