# Generated by Django 5.1.8 on 2025-04-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_tienda_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
