# Generated by Django 5.1.7 on 2025-04-30 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_inventario_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('direccion_envio', models.CharField(max_length=255)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.coche')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='coches',
            field=models.ManyToManyField(through='tienda.Pedidos', to='tienda.coche'),
        ),
    ]
